% 嵌入在main2.m中
%% ****** 二、日内阶段 ***************************************
% 日内调度参考数值，96 --> 288，用于计算调整成本。虽然只有迭代结束保存的向量才有96个实际的值，但是这里用不到那么多，每次迭代即使不完整也不影响。
P_g2gt_save2_288 = repmat(P_g2gt_save2', 3, 1);      % 1x96 --> 3x96
P_g2gt_save2_288 = reshape(P_g2gt_save2_288, [], 1); % 3x96 --> 288x1
P_g2gb_save2_288 = repmat(P_g2gb_save2', 3, 1);      % 1x96 --> 3x96
P_g2gb_save2_288 = reshape(P_g2gb_save2_288, [], 1); % 3x96 --> 288x1

P_e2el_save2_288 = repmat(P_e2el_save2', 3, 1);      
P_e2el_save2_288 = reshape(P_e2el_save2_288, [], 1); 
P_H2mr_save2_288 = repmat(P_H2mr_save2', 3, 1);      
P_H2mr_save2_288 = reshape(P_H2mr_save2_288, [], 1); 
P_e2eb_save2_288 = repmat(P_e2eb_save2', 3, 1);      
P_e2eb_save2_288 = reshape(P_e2eb_save2_288, [], 1); 

P_hst_cha_save2_288 = repmat(P_hst_cha_save2', 3, 1);
P_hst_cha_save2_288 = reshape(P_hst_cha_save2_288, [], 1);
P_hst_dis_save2_288 = repmat(P_hst_dis_save2', 3, 1);
P_hst_dis_save2_288 = reshape(P_hst_dis_save2_288, [], 1);

P_tst_cha_save2_288 = repmat(P_tst_cha_save2', 3, 1);
P_tst_cha_save2_288 = reshape(P_tst_cha_save2_288, [], 1);
P_tst_dis_save2_288 = repmat(P_tst_dis_save2', 3, 1);
P_tst_dis_save2_288 = reshape(P_tst_dis_save2_288, [], 1);

P_gst_cha_save2_288 = repmat(P_gst_cha_save2', 3, 1);
P_gst_cha_save2_288 = reshape(P_gst_cha_save2_288, [], 1);
P_gst_dis_save2_288 = repmat(P_gst_dis_save2', 3, 1);
P_gst_dis_save2_288 = reshape(P_gst_dis_save2_288, [], 1);

% 日内DR_CL，96 --> 288
L_edr_cl_save2_288 = repmat(L_edr_cl_save2', 3, 1); L_edr_cl_save2_288 = reshape(L_edr_cl_save2_288, [], 1);
L_hdr_cl_save2_288 = repmat(L_hdr_cl_save2', 3, 1); L_hdr_cl_save2_288 = reshape(L_hdr_cl_save2_288, [], 1);

% 日前DR_CL响应量，24 --> 288，日前DR_SL响应量，24 --> 96
% 在main.2文件中已经定义过了

% 电价、气价，15min一个点，24h一共96个点
c_pur_e_288 = repmat(c_pur_e, 12, 1);
c_pur_e_288 = reshape(c_pur_e_288, [], 1);  % 1h的数据变为12个相同的5min数据
c_pur_g_288 = repmat(c_pur_g, 12, 1);
c_pur_g_288 = reshape(c_pur_g_288, [], 1);  % 1h的数据变为12个相同的5min数据

%% ****** 三、实时阶段 ***************************************
%% ======== 1.实时-决策变量定义 ===================================
% 在for i=1:4:81之外已经定义过了
%% ======== 2.运行约束 ===================================
if i ~= 81                                                  % 注意：本文件运行在日内for循环的内层，i是外层for的循环变量，禁止点击修复，忽略这种警告
    for j=1:3:10  % 30min-5min, 15min滚动一次，所以i+3，j：1,4,7,10
        OBJECTIVE_3 = 0;
        CONSTRAINTS_3 = [];
        % ==================== 公共参数 ====================
        % 使用相对索引推导出绝对索引位置，5min数据一共288个
        idx_start = (i-1)*3 + j;                            % 注意：本文件运行在日内for循环的内层，i是外层for的循环变量，禁止点击修复，忽略这种警告
        idx_end = (i-1)*3 + j + 5;
        % ==================== 源荷参数 ====================
        P_wt2e_max_3 = P_wt2e_5min_pre(idx_start:idx_end);
        P_pv2e_max_3 = P_pv2e_5min_pre(idx_start:idx_end);
        P_eLoad_3 = P_eLoad_5min_pre(idx_start:idx_end);
        P_hLoad_3 = P_hLoad_5min_pre(idx_start:idx_end);
        % ==================== 电价气价 ====================
        c_pur_e_3 = c_pur_e_288(idx_start:idx_end);
        c_pur_g_3 = c_pur_g_288(idx_start:idx_end);
        % ==================== 日内功率参考值，用于计算调整成本 ====================
        P_g2gt_save2_3 = P_g2gt_save2_288(idx_start:idx_end);
        P_g2gb_save2_3 = P_g2gb_save2_288(idx_start:idx_end);
    
        P_e2el_save2_3 = P_e2el_save2_288(idx_start:idx_end);
        P_H2mr_save2_3 = P_H2mr_save2_288(idx_start:idx_end);
        P_e2eb_save2_3 = P_e2eb_save2_288(idx_start:idx_end);
    
        P_hst_cha_save2_3 = P_hst_cha_save2_288(idx_start:idx_end);
        P_hst_dis_save2_3 = P_hst_dis_save2_288(idx_start:idx_end);
        P_tst_cha_save2_3 = P_tst_cha_save2_288(idx_start:idx_end);
        P_tst_dis_save2_3 = P_tst_dis_save2_288(idx_start:idx_end);
        P_gst_cha_save2_3 = P_gst_cha_save2_288(idx_start:idx_end);
        P_gst_dis_save2_3 = P_gst_dis_save2_288(idx_start:idx_end);
        % ==================== 日前DR_CL响应量 ====================
        L_edr_cl_save1_3 = L_edr_cl_save1_288(idx_start:idx_end);
        L_hdr_cl_save1_3 = L_hdr_cl_save1_288(idx_start:idx_end);
        % ==================== 日前DR_SL响应量 ====================
        L_edr_sl_in_save1_3 = L_edr_sl_in_save1_288(idx_start:idx_end);
        L_edr_sl_out_save1_3 = L_edr_sl_out_save1_288(idx_start:idx_end);
        L_hdr_sl_in_save1_3 = L_hdr_sl_in_save1_288(idx_start:idx_end);
        L_hdr_sl_out_save1_3 = L_hdr_sl_out_save1_288(idx_start:idx_end);
        % ==================== 日内DR响应量 ====================
        L_edr_cl_save2_3 = L_edr_cl_save2_288(idx_start:idx_end);
        L_hdr_cl_save2_3 = L_hdr_cl_save2_288(idx_start:idx_end);
        % 风机光伏
        CONSTRAINTS_3 = [CONSTRAINTS_3,...
            (0 <= P_wt2e_3 <= P_wt2e_max_3): 'P_wt2e_3',...
            (0 <= P_pv2e_3 <= P_pv2e_max_3): 'P_pv2e_3'
            ];
        % 笔记
        % 约束：首尾Delta、中间Delta、中间相等
        % EL电解槽（爬升约束）
        temp_el_3 = reshape(P_e2el_3, 3, []);  % 只是P_e2el_3的另一种视图，本质还是在操作P_e2el_3
        if i == 1 && j == 1
            CONSTRAINTS_3 = [CONSTRAINTS_3,...
                (P_el2H_3 == f_el * P_e2el_3): 'P_el2H_3',...
                (P_el_min <= P_e2el_3 <= P_el_max): 'P_e2el_3',...
                (-Delta_el*P_el_max/4 <= P_e2el_3(4)-P_e2el_3(3) <= Delta_el*P_el_max/4): 'P_e2el_Delta',...
                (temp_el_3(1:2, :) == temp_el_3(2:3, :))
                ];
        else
            CONSTRAINTS_3 = [CONSTRAINTS_3,...
                (P_el2H_3 == f_el * P_e2el_3): 'P_el2H_3',...
                (P_el_min <= P_e2el_3 <= P_el_max): 'P_e2el_3',...
                (-Delta_el*P_el_max/4 <= P_e2el_3(1)-P_e2el_save3(idx_start-1) <= Delta_el*P_el_max/4): 'P_e2el(0)_Delta',...
                (-Delta_el*P_el_max/4 <= P_e2el_3(4)-P_e2el_3(3) <= Delta_el*P_el_max/4): 'P_e2el_Delta',...
                (temp_el_3(1:2, :) == temp_el_3(2:3, :))
                ];
        end
        % MR甲烷反应器（爬升约束）
        temp_mr_3 = reshape(P_H2mr_3, 3, []);  % 只是P_H2mr_3的另一种视图，本质还是在操作P_H2mr_3
        if i == 1 && j == 1
            CONSTRAINTS_3 = [CONSTRAINTS_3,...
                (P_mr2g_3 == f_mr * P_H2mr_3): 'P_mr2g_3',...
                (P_mr_min <= P_H2mr_3 <= P_mr_max): 'P_H2mr_3',...
                (-Delta_mr*P_mr_max/4 <= P_H2mr_3(4)-P_H2mr_3(3) <= Delta_mr*P_mr_max/4): 'P_H2mr_Delta',...
                (temp_mr_3(1:2, :) == temp_mr_3(2:3, :))
                ];
        else
            CONSTRAINTS_3 = [CONSTRAINTS_3,...
                (P_mr2g_3 == f_mr * P_H2mr_3): 'P_mr2g_3',...
                (P_mr_min <= P_H2mr_3 <= P_mr_max): 'P_H2mr_3',...
                (-Delta_mr*P_mr_max/4 <= P_H2mr_3(1)-P_H2mr_save3(idx_start-1) <= Delta_mr*P_mr_max/4): 'P_H2mr(0)_Delta',...
                (-Delta_mr*P_mr_max/4 <= P_H2mr_3(4)-P_H2mr_3(3) <= Delta_mr*P_mr_max/4): 'P_H2mr_Delta',...
                (temp_mr_3(1:2, :) == temp_mr_3(2:3, :))
                ];
        end
        % HFC燃料电池（爬升约束）
        if i == 1 && j == 1
            CONSTRAINTS_3 = [CONSTRAINTS_3,...
                (P_hfc2e_3 == f_hfc_H2e * P_H2hfc_3): 'P_hfc2e_3',...
                (P_hfc2h_3 == f_hfc_H2h * P_H2hfc_3): 'P_hfc2h_3',...
                (P_hfc2e_3 + P_hfc2h_3 == (f_hfc_H2e+f_hfc_H2h) * P_H2hfc_3): 'P_hfc2e_3 + P_hfc2h_3',...
                (P_hfc_min <= P_H2hfc_3 <= P_hfc_max): 'P_H2hfc_3',...
                (-Delta_hfc*P_hfc_max/12 <= P_H2hfc_3(2:end)-P_H2hfc_3(1:end-1) <= Delta_hfc*P_hfc_max/12): 'P_H2hfc_Delta'
                ];
        else
            CONSTRAINTS_3 = [CONSTRAINTS_3,...
                (P_hfc2e_3 == f_hfc_H2e * P_H2hfc_3): 'P_hfc2e_3',...
                (P_hfc2h_3 == f_hfc_H2h * P_H2hfc_3): 'P_hfc2h_3',...
                (P_hfc2e_3 + P_hfc2h_3 == (f_hfc_H2e+f_hfc_H2h) * P_H2hfc_3): 'P_hfc2e_3 + P_hfc2h_3',...
                (P_hfc_min <= P_H2hfc_3 <= P_hfc_max): 'P_H2hfc_3',...
                (-Delta_hfc*P_hfc_max/12 <= P_H2hfc_3(1)-P_H2hfc_save3(idx_start-1) <= Delta_hfc*P_hfc_max/12): 'P_H2hfc(0)_Delta',...
                (-Delta_hfc*P_hfc_max/12 <= P_H2hfc_3(2:end)-P_H2hfc_3(1:end-1) <= Delta_hfc*P_hfc_max/12): 'P_H2hfc_Delta'
                ];
        end
        % GT燃气轮机（爬升约束）
        temp_gt_3 = reshape(P_g2gt_3, 3, []);    % 6x1 --> 3x2
        if i == 1 && j == 1
            CONSTRAINTS_3 = [CONSTRAINTS_3,...
                (P_g2gt_3 == (LHV_CH4 * M_g2gt_3 + LHV_H2 * M_H2gt_3) ): 'M_H2gt_3',...
                (V_g2gt_3 == M_g2gt_3 / density_CH4): 'V_g2gt_3',...
                (V_H2gt_3 == M_H2gt_3 / density_H2): 'V_H2gt_3',...
                (V_H2gt_3 <= k_H2gt_upper * (V_g2gt_3 + V_H2gt_3)): 'k_H2gt_upper',...
                (V_H2gt_3 >= k_H2gt_lower * (V_g2gt_3 + V_H2gt_3)): 'k_H2gt_lower',...
                (P_gt2e_3 == f_gt_g2e * P_g2gt_3): 'P_gt2e_3',...
                (P_gt2h_3 == f_gt_g2h * P_g2gt_3): 'P_gt2h_3',...
                (P_gt2e_3 + P_gt2h_3 == (f_gt_g2e+f_gt_g2h) * P_g2gt_3): 'P_gt2e_3 + P_gt2h_3',...
                (P_gt_min <= P_g2gt_3 <= P_gt_max): 'P_g2gt_3',...
                (P_g2gt_3(2:end) == P_g2gt_3(1:end-1)),...
                (M_g2gt_3 >= 0),...
                (M_H2gt_3 >= 0)
                ];
        elseif (i ~= 1 && j ==1) || j == 7
            CONSTRAINTS_3 = [CONSTRAINTS_3,...
                (P_g2gt_3 == (LHV_CH4 * M_g2gt_3 + LHV_H2 * M_H2gt_3) ): 'M_H2gt_3',...
                (V_g2gt_3 == M_g2gt_3 / density_CH4): 'V_g2gt_3',...
                (V_H2gt_3 == M_H2gt_3 / density_H2): 'V_H2gt_3',...
                (V_H2gt_3 <= k_H2gt_upper * (V_g2gt_3 + V_H2gt_3)): 'k_H2gt_upper',...
                (V_H2gt_3 >= k_H2gt_lower * (V_g2gt_3 + V_H2gt_3)): 'k_H2gt_lower',...
                (P_gt2e_3 == f_gt_g2e * P_g2gt_3): 'P_gt2e_3',...
                (P_gt2h_3 == f_gt_g2h * P_g2gt_3): 'P_gt2h_3',...
                (P_gt2e_3 + P_gt2h_3 == (f_gt_g2e+f_gt_g2h) * P_g2gt_3): 'P_gt2e_3 + P_gt2h_3',...
                (P_gt_min <= P_g2gt_3 <= P_gt_max): 'P_g2gt_3',...
                (-Delta_gt*P_gt_max/2 <= P_g2gt_3(1) - P_g2gt_save3(idx_start-1) <= Delta_gt*P_gt_max/2): 'P_g2gt(0)_Detla',...
                (P_g2gt_3(2:end) == P_g2gt_3(1:end-1)),...
                (M_g2gt_3 >= 0),...
                (M_H2gt_3 >= 0)
                ];
        elseif j == 4 || j == 10
            CONSTRAINTS_3 = [CONSTRAINTS_3,...
                (P_g2gt_3 == (LHV_CH4 * M_g2gt_3 + LHV_H2 * M_H2gt_3) ): 'M_H2gt_3',...
                (V_g2gt_3 == M_g2gt_3 / density_CH4): 'V_g2gt_3',...
                (V_H2gt_3 == M_H2gt_3 / density_H2): 'V_H2gt_3',...
                (V_H2gt_3 <= k_H2gt_upper * (V_g2gt_3 + V_H2gt_3)): 'k_H2gt_upper',...
                (V_H2gt_3 >= k_H2gt_lower * (V_g2gt_3 + V_H2gt_3)): 'k_H2gt_lower',...
                (P_gt2e_3 == f_gt_g2e * P_g2gt_3): 'P_gt2e_3',...
                (P_gt2h_3 == f_gt_g2h * P_g2gt_3): 'P_gt2h_3',...
                (P_gt2e_3 + P_gt2h_3 == (f_gt_g2e+f_gt_g2h) * P_g2gt_3): 'P_gt2e_3 + P_gt2h_3',...
                (P_gt_min <= P_g2gt_3 <= P_gt_max): 'P_g2gt_3',...
                (-Delta_gt*P_gt_max/2 <= P_g2gt_3(1) - P_g2gt_save3(idx_start-1) <= Delta_gt*P_gt_max/2): 'P_g2gt(0)_Detla',...
                (-Delta_gt*P_gt_max/2 <= P_g2gt_3(4) - P_g2gt_3(3) <= Delta_gt*P_gt_max/2): 'P_g2gt_3_Detla',...
                (temp_gt_3(1:2, :) == temp_gt_3(2:3, :)),...
                (M_g2gt_3 >= 0),...
                (M_H2gt_3 >= 0)
                ];
        end
        % GB燃气轮机（爬升约束）
        temp_gb_3 = reshape(P_g2gb_3, 3, []);    % 6x1 --> 3x2
        if i == 1 && j == 1
            CONSTRAINTS_3 = [CONSTRAINTS_3,...
                (P_g2gb_3 == (LHV_CH4 * M_g2gb_3 + LHV_H2 * M_H2gb_3) ): 'M_H2gb_3',...
                (V_g2gb_3 == M_g2gb_3 / density_CH4): 'V_g2gb_3',...
                (V_H2gb_3 == M_H2gb_3 / density_H2): 'V_H2gb_3',...
                (V_H2gb_3 <= k_H2gb_upper * (V_g2gb_3 + V_H2gb_3)): 'k_H2gb_upper',...
                (V_H2gb_3 >= k_H2gb_lower * (V_g2gb_3 + V_H2gb_3)): 'k_H2gb_lower',...
                (P_gb2h_3 == f_gb * P_g2gb_3): 'P_gb2h_3',...
                (P_gb_min <= P_g2gb_3 <= P_gb_max): 'P_g2gb_3',...
                (P_g2gb_3(2:end) == P_g2gb_3(1:end-1)),...
                (M_g2gb_3 >= 0),...
                (M_H2gb_3 >= 0)
                ];
        elseif (i ~= 1 && j ==1) || j == 7
            CONSTRAINTS_3 = [CONSTRAINTS_3,...
                (P_g2gb_3 == (LHV_CH4 * M_g2gb_3 + LHV_H2 * M_H2gb_3) ): 'M_H2gb_3',...
                (V_g2gb_3 == M_g2gb_3 / density_CH4): 'V_g2gb_3',...
                (V_H2gb_3 == M_H2gb_3 / density_H2): 'V_H2gb_3',...
                (V_H2gb_3 <= k_H2gb_upper * (V_g2gb_3 + V_H2gb_3)): 'k_H2gb_upper',...
                (V_H2gb_3 >= k_H2gb_lower * (V_g2gb_3 + V_H2gb_3)): 'k_H2gb_lower',...
                (P_gb2h_3 == f_gb * P_g2gb_3): 'P_gb2h_3',...
                (P_gb_min <= P_g2gb_3 <= P_gb_max): 'P_g2gb_3',...
                (-Delta_gb*P_gb_max/2 <= P_g2gb_3(1) - P_g2gb_save3(idx_start-1) <= Delta_gb*P_gb_max/2): 'P_g2gb(0)_Detla',...
                (P_g2gb_3(2:end) == P_g2gb_3(1:end-1)),...
                (M_g2gb_3 >= 0),...
                (M_H2gb_3 >= 0)
                ];
        elseif j == 4 || j == 10
            CONSTRAINTS_3 = [CONSTRAINTS_3,...
                (P_g2gb_3 == (LHV_CH4 * M_g2gb_3 + LHV_H2 * M_H2gb_3) ): 'M_H2gb_3',...
                (V_g2gb_3 == M_g2gb_3 / density_CH4): 'V_g2gb_3',...
                (V_H2gb_3 == M_H2gb_3 / density_H2): 'V_H2gb_3',...
                (V_H2gb_3 <= k_H2gb_upper * (V_g2gb_3 + V_H2gb_3)): 'k_H2gb_upper',...
                (V_H2gb_3 >= k_H2gb_lower * (V_g2gb_3 + V_H2gb_3)): 'k_H2gb_lower',...
                (P_gb2h_3 == f_gb * P_g2gb_3): 'P_gb2h_3',...
                (P_gb_min <= P_g2gb_3 <= P_gb_max): 'P_g2gb_3',...
                (-Delta_gb*P_gb_max/2 <= P_g2gb_3(1) - P_g2gb_save3(idx_start-1) <= Delta_gb*P_gb_max/2): 'P_g2gb(0)_Detla',...
                (-Delta_gb*P_gb_max/2 <= P_g2gb_3(4) - P_g2gb_3(3) <= Delta_gb*P_gb_max/2): 'P_g2gb_3_Detla',...
                (temp_gb_3(1:2, :) == temp_gb_3(2:3, :)),...
                (M_g2gb_3 >= 0),...
                (M_H2gb_3 >= 0)
                ];
        end
        % EB电锅炉（爬升约束）
        temp_eb_3 = reshape(P_e2eb_3, 3, []);
        if i == 1 && j == 1
            CONSTRAINTS_3 = [CONSTRAINTS_3,...
                (P_eb2h_3 == f_eb * P_e2eb_3): 'P_eb2h_3',...
                (P_eb_min <= P_e2eb_3 <= P_eb_max): 'P_e2eb_3',...
                (-Delta_eb*P_eb_max/4 <= P_e2eb_3(4)-P_e2eb_3(3) <= Delta_eb*P_eb_max/4): 'P_e2eb_Delta',...
                (temp_eb_3(1:2, :) == temp_eb_3(2:3, :))
                ];
        else
            CONSTRAINTS_3 = [CONSTRAINTS_3,...
                (P_eb2h_3 == f_eb * P_e2eb_3): 'P_eb2h_3',...
                (P_eb_min <= P_e2eb_3 <= P_eb_max): 'P_e2eb_3',...
                (-Delta_eb*P_eb_max/4 <= P_e2eb_3(1)-P_e2eb_save3(idx_start-1) <= Delta_eb*P_eb_max/4): 'P_e2eb(0)_Delta',...
                (-Delta_eb*P_eb_max/4 <= P_e2eb_3(4)-P_e2eb_3(3) <= Delta_eb*P_eb_max/4): 'P_e2eb_Delta',...
                (temp_eb_3(1:2, :) == temp_eb_3(2:3, :))
                ];
        end
        %% ======== 3.储能约束 ===================================
        % 储电约束Battery，充放能倍率选择0.5C
        if i == 1 && j == 1
            CONSTRAINTS_3 = [CONSTRAINTS_3,...
                (0 <= P_bat_cha_3 <= Flag_bat_cha_3 * Q_bat_max * 0.5): 'P_bat_cha_3',...
                (0 <= P_bat_dis_3 <= Flag_bat_dis_3 * Q_bat_max * 0.5): 'P_bat_dis_3',...
                (Flag_bat_cha_3 + Flag_bat_dis_3 <= 1): 'Flag_bat',...
                (SOC_bat_3(1) == f_bat_init): 'SOC_bat_init',...
                (f_bat_min <= SOC_bat_3 <= f_bat_max): 'SOC_bat_range',...
                (SOC_bat_3(2:end) == SOC_bat_3(1:end-1) + f_bat_cha/(Q_bat_max*12)*P_bat_cha_3 - P_bat_dis_3/(f_bat_dis*Q_bat_max*12)): 'SOC_bat_Delta'
                ];
        else
            CONSTRAINTS_3 = [CONSTRAINTS_3,...
                (0 <= P_bat_cha_3 <= Flag_bat_cha_3 * Q_bat_max * 0.5): 'P_bat_cha_3',...
                (0 <= P_bat_dis_3 <= Flag_bat_dis_3 * Q_bat_max * 0.5): 'P_bat_dis_3',...
                (Flag_bat_cha_3 + Flag_bat_dis_3 <= 1): 'Flag_bat',...
                (SOC_bat_3(1) == SOC_bat_save3(idx_start)): 'SOC_bat_init',...
                (f_bat_min <= SOC_bat_3 <= f_bat_max): 'SOC_bat_range',...
                (SOC_bat_3(2:end) == SOC_bat_3(1:end-1) + f_bat_cha/(Q_bat_max*12)*P_bat_cha_3 - P_bat_dis_3/(f_bat_dis*Q_bat_max*12)): 'SOC_bat_Delta'
                ];
        end
        % 储氢约束HST
        if i == 1 && j == 1
            CONSTRAINTS_3 = [CONSTRAINTS_3,...
                (0 <= P_hst_cha_3 <= Flag_hst_cha_3 * Q_hst_max * 0.5): 'P_hst_cha_3',...
                (0 <= P_hst_dis_3 <= Flag_hst_dis_3 * Q_hst_max * 0.5): 'P_hst_dis_3',...
                (Flag_hst_cha_3 + Flag_hst_dis_3 <= 1): 'Flag_hst',...
                (SOC_hst_3(1) == f_hst_init): 'SOC_hst_init',...
                (f_hst_min <= SOC_hst_3 <= f_hst_max): 'SOC_hst_range',...
                (SOC_hst_3(2:end) == SOC_hst_3(1:end-1) + f_hst_cha/(Q_hst_max*12)*P_hst_cha_3 - P_hst_dis_3/(f_hst_dis*Q_hst_max*12)): 'SOC_hst_Delta'
                ];
        else
            CONSTRAINTS_3 = [CONSTRAINTS_3,...
                (0 <= P_hst_cha_3 <= Flag_hst_cha_3 * Q_hst_max * 0.5): 'P_hst_cha_3',...
                (0 <= P_hst_dis_3 <= Flag_hst_dis_3 * Q_hst_max * 0.5): 'P_hst_dis_3',...
                (Flag_hst_cha_3 + Flag_hst_dis_3 <= 1): 'Flag_hst',...
                (SOC_hst_3(1) == SOC_hst_save3(idx_start)): 'SOC_hst_init',...
                (f_hst_min <= SOC_hst_3 <= f_hst_max): 'SOC_hst_range',...
                (SOC_hst_3(2:end) == SOC_hst_3(1:end-1) + f_hst_cha/(Q_hst_max*12)*P_hst_cha_3 - P_hst_dis_3/(f_hst_dis*Q_hst_max*12)): 'SOC_hst_Delta'
                ];
        end
        % 储热约束TST
        if i == 1 && j == 1
            CONSTRAINTS_3 = [CONSTRAINTS_3,...
                (0 <= P_tst_cha_3 <= Flag_tst_cha_3 * Q_tst_max * 0.5): 'P_tst_cha_3',...
                (0 <= P_tst_dis_3 <= Flag_tst_dis_3 * Q_tst_max * 0.5): 'P_tst_dis_3',...
                (Flag_tst_cha_3 + Flag_tst_dis_3 <= 1): 'Flag_tst',...
                (SOC_tst_3(1) == f_tst_init): 'SOC_tst_init',...
                (f_tst_min <= SOC_tst_3 <= f_tst_max): 'SOC_tst_range',...
                (SOC_tst_3(2:end) == SOC_tst_3(1:end-1) + f_tst_cha/(Q_tst_max*12)*P_tst_cha_3 - P_tst_dis_3/(f_tst_dis*Q_tst_max*12)): 'SOC_tst_Delta'
                ];
        else
            CONSTRAINTS_3 = [CONSTRAINTS_3,...
                (0 <= P_tst_cha_3 <= Flag_tst_cha_3 * Q_tst_max * 0.5): 'P_tst_cha_3',...
                (0 <= P_tst_dis_3 <= Flag_tst_dis_3 * Q_tst_max * 0.5): 'P_tst_dis_3',...
                (Flag_tst_cha_3 + Flag_tst_dis_3 <= 1): 'Flag_tst',...
                (SOC_tst_3(1) == SOC_tst_save3(idx_start)): 'SOC_tst_init',...
                (f_tst_min <= SOC_tst_3 <= f_tst_max): 'SOC_tst_range',...
                (SOC_tst_3(2:end) == SOC_tst_3(1:end-1) + f_tst_cha/(Q_tst_max*12)*P_tst_cha_3 - P_tst_dis_3/(f_tst_dis*Q_tst_max*12)): 'SOC_tst_Delta'
                ];
        end
        % 储气约束GST
        if i == 1 && j == 1
            CONSTRAINTS_3 = [CONSTRAINTS_3,...
                (0 <= P_gst_cha_3 <= Flag_gst_cha_3 * Q_gst_max * 0.5): 'P_gst_cha_3',...
                (0 <= P_gst_dis_3 <= Flag_gst_dis_3 * Q_gst_max * 0.5): 'P_gst_dis_3',...
                (Flag_gst_cha_3 + Flag_gst_dis_3 <= 1): 'Flag_gst',...
                (SOC_gst_3(1) == f_gst_init): 'SOC_gst_init',...
                (f_gst_min <= SOC_gst_3 <= f_gst_max): 'SOC_gst_range',...
                (SOC_gst_3(2:end) == SOC_gst_3(1:end-1) + f_gst_cha/(Q_gst_max*12)*P_gst_cha_3 - P_gst_dis_3/(f_gst_dis*Q_gst_max*12)): 'SOC_gst_Delta'
                ];
        else
            CONSTRAINTS_3 = [CONSTRAINTS_3,...
                (0 <= P_gst_cha_3 <= Flag_gst_cha_3 * Q_gst_max * 0.5): 'P_gst_cha_3',...
                (0 <= P_gst_dis_3 <= Flag_gst_dis_3 * Q_gst_max * 0.5): 'P_gst_dis_3',...
                (Flag_gst_cha_3 + Flag_gst_dis_3 <= 1): 'Flag_gst',...
                (SOC_gst_3(1) == SOC_gst_save3(idx_start)): 'SOC_gst_init',...
                (f_gst_min <= SOC_gst_3 <= f_gst_max): 'SOC_gst_range',...
                (SOC_gst_3(2:end) == SOC_gst_3(1:end-1) + f_gst_cha/(Q_gst_max*12)*P_gst_cha_3 - P_gst_dis_3/(f_gst_dis*Q_gst_max*12)): 'SOC_gst_Delta'
                ];
        end

        %% ======== 4.1购能约束 ===================================
        % 购电、购气约束
        CONSTRAINTS_3 = [CONSTRAINTS_3,...
            (0 <= P_pur_e_3 <= P_pur_e_max): 'P_pur_e_3',...
            (0 <= P_pur_g_3 <= P_pur_g_max): 'P_pur_g_3'
            ];
        %% ======== 4.2DR约束 ===================================
        CONSTRAINTS_3 = [CONSTRAINTS_3,...
            (0 <= L_edr_cl_3 <= L_edr_cl_max_3): 'L_edr_cl_3',...
            (0 <= L_hdr_cl_3 <= L_hdr_cl_max_3): 'L_hdr_cl_3'
            ];
        %% ======== 4.3阶梯碳交易 ===================================
        % 实际碳排放，这里只计算天然气部分产生的二氧化碳
        E_actu_e2pur_3 = sum( k_SC_a + k_SC_b*P_pur_e_3 + k_SC_c*(P_pur_e_3.^2) ) / 12;          % 电网实际碳排放量
        P_gt_total_3 = LHV_CH4*M_g2gt_3*f_gt_g2e*phi_eh + LHV_CH4*M_g2gt_3*f_gt_g2h;
        E_actu_gt_3 = sum( k_gas_a + k_gas_b*P_gt_total_3 + k_gas_c*(P_gt_total_3.^2) ) / 12;    % GT实际碳排放量
        P_gb_total_3 = LHV_CH4*M_g2gb_3*f_gb;
        E_actu_gb_3 = sum( k_gas_a + k_gas_b*P_gb_total_3 + k_gas_c*(P_gb_total_3.^2) ) / 12;    % GB实际碳排放量
        E_actu_total_3 = E_actu_e2pur_3 + E_actu_gt_3 + E_actu_gb_3;
        % CCS吸收碳排放量
        E_ccs_total_3 = sum( P_mr2g_3 / LHV_CH4 * w_mr) / 12;
        CONSTRAINTS_3 = [CONSTRAINTS_3,...
            (P_e2ccs_3 == P_mr2g_3 / LHV_CH4 * w_mr * f_ccus): 'P_e2ccs_3'
            ];
        % 碳配额部分
        E_pe_total_3 = E_pe_total_save1 / (E_actu_total_save1 - E_ccs_total_save1) * (E_actu_total_3 - E_ccs_total_3);
        % 碳交易
        E_tra_3 = E_actu_total_3 - E_pe_total_3 - E_ccs_total_3;     % 参与碳交易的二氧化碳量
        C_lad_CO2_3 = c_lad_di_da * E_tra_3;
     

        %% ======== 5.功率平衡约束 ===================================
        CONSTRAINTS_3 = [CONSTRAINTS_3,...
            ... 电平衡：风光发电 + 电网购电 + GT发电 + HFC发电 + 电池放电 = 电负荷 + EL电解槽电解 + EB电锅炉用电 + CCS用电 + 电池充电 -日前DR_CL+日前DR_SL_in-日前DR_SL_out-日内DR_CL-实时DR_CL
            (P_wt2e_3+P_pv2e_3+P_pur_e_3+P_gt2e_3+P_hfc2e_3+P_bat_dis_3 ==  P_eLoad_3+P_e2el_3+P_e2eb_3+P_e2ccs_3+P_bat_cha_3-L_edr_cl_save1_3+L_edr_sl_in_save1_3-L_edr_sl_out_save1_3-L_edr_cl_save2_3-L_edr_cl_3): 'P_e_balance',...
            ... 热平衡：GT产热 + GB产热 + HFC产热 + EB产热 + 储热放热 = 热负荷 + 储热吸热 -日前DR_CL+日前DR_SL_in-日前DR_SL_out-日内DR_CL-实时DR_CL
            (P_gt2h_3 + P_gb2h_3 + P_hfc2h_3 + P_eb2h_3 + P_tst_dis_3 == P_hLoad_3 + P_tst_cha_3-L_hdr_cl_save1_3+L_hdr_sl_in_save1_3-L_hdr_sl_out_save1_3-L_hdr_cl_save2_3-L_hdr_cl_3): 'P_h_balance',...
            ... 氢平衡：EL产氢 + 储氢放氢 = HFC用氢 + MR用氢 + GT用氢 + GB用氢 + 储氢充氢
            (P_el2H_3 + P_hst_dis_3 == P_H2hfc_3 + P_H2mr_3 + LHV_H2*M_H2gt_3 + LHV_H2*M_H2gb_3 + P_hst_cha_3): 'P_H_balance',...
            ... 气平衡：气网购气 + MR产气 + 储气放气 = GT用气 + GB用气 + 储气充气
            (P_pur_g_3 + P_mr2g_3 + P_gst_dis_3 == LHV_CH4*M_g2gt_3 + LHV_CH4*M_g2gb_3 + P_gst_cha_3): 'P_g_balance'
            ];
        %% ======== 6.目标函数 ===================================
        % ==================== 运维成本 ====================
        C_opm_3 = ( sum(P_wt2e_3)*c_opm_wt + sum(P_pv2e_3)*c_opm_pv + sum(P_e2el_3)*c_opm_el + sum(P_H2hfc_3)*c_opm_hfc + ...
            sum(P_g2gt_3)*c_opm_gt + sum(P_g2gb_3)*c_opm_gb + sum(P_e2eb_3)*c_opm_eb ) / 12;
        % ==================== 购能成本 ====================
        % 注意：天然气价格为 元/m3，所以需要转换单位
        C_pur_3 = ( sum(P_pur_e_3.*c_pur_e_3) + sum( P_pur_g_3 / (LHV_CH4 * density_CH4) .* c_pur_g_3 )) / 12;
        % ==================== 储能成本 ====================
        C_st_3 = ( sum(P_bat_cha_3+P_bat_dis_3)*c_st_bat + sum(P_hst_cha_3+P_hst_dis_3)*c_st_hst + sum(P_tst_cha_3+P_tst_dis_3)*c_st_tst + ...
            sum(P_gst_cha_3+P_gst_dis_3)*c_st_gst ) / 12;
        % ==================== 弃能成本 ====================
        C_abd_3 = ( sum(P_wt2e_max_3 - P_wt2e_3)*c_abd_wt + sum(P_pv2e_max_3 - P_pv2e_3)*c_abd_pv ) / 12;
        % ==================== 调整成本（新增） ====================
        C_adj_3 = ( sum(abs(P_g2gt_3 - P_g2gt_save2_3))*c_adj_3 + sum(abs(P_g2gb_3 - P_g2gb_save2_3)) * c_adj_3 + ...
            sum(abs(P_e2el_3 - P_e2el_save2_3))*c_adj_3 + sum(abs(P_H2mr_3 - P_H2mr_save2_3)) * c_adj_3 + sum(abs(P_e2eb_3 - P_e2eb_save2_3)) * c_adj_3 +...
            sum(abs(P_hst_cha_3 - P_hst_cha_save2_3))*c_adj_3 +  sum(abs(P_hst_dis_3 - P_hst_dis_save2_3))*c_adj_3 + ...
            sum(abs(P_tst_cha_3 - P_tst_cha_save2_3))*c_adj_3 +  sum(abs(P_tst_dis_3 - P_tst_dis_save2_3))*c_adj_3 + ...
            sum(abs(P_gst_cha_3 - P_gst_cha_save2_3))*c_adj_3 +  sum(abs(P_gst_dis_3 - P_gst_dis_save2_3))*c_adj_3 ) / 12;
        % ==================== DR成本 ====================
        C_dr_3 = ( sum(L_edr_cl_3)*c_edr_cl_3 + sum(L_hdr_cl_3)*c_hdr_cl_3 ) / 12;
        %% ======== 7.求解 ===================================
        OBJECTIVE_3 = OBJECTIVE_3 + C_opm_3 + C_pur_3 + C_st_3 + C_abd_3 + C_adj_3 + C_dr_3 + C_lad_CO2_3;
        OPTIONS = sdpsettings('solver', 'cplex', 'verbose', 0, 'showprogress', 0);
        % 在数学优化中，容差参数用于处理数值计算中的舍入误差和数值不稳定性。由于计算机使用浮点数运算，严格的等式约束在实际中很难完全满足。
        OPTIONS.cplex.eprhs = 1e-6;     % 可行性容差
        OPTIONS.cplex.epopt = 1e-6;     % 最优性容差
        sol = optimize(CONSTRAINTS_3, OBJECTIVE_3, OPTIONS);
    
        if sol.problem == 0
            win = (j-1)/3 + 1;
            fprintf("    实时滚动窗口 %d（起点索引 i=%d）求解成功\n", win, j);
    
        else 
            disp("    出错了，原因是：");
            disp(sol.info);
    
            % 正确的调试方法
            if sol.problem == 1
                disp("    问题不可行，检查约束条件");
                % 检查哪些约束不满足
                disp("    检查约束可行性:");
                check(CONSTRAINTS_3);
            else
                disp(["    求解器返回代码: ", num2str(sol.problem)]);
            end
        end  %if sol.problem == 0 
    
    
        %% ======== 8.保存30min-5min求解值 ===================================
        if IF_VALUE_Realtime        
            %-------------------------------------------设备决策变量保存
            P_wt2e_save3(idx_start:idx_end) = zero_tiny(value(P_wt2e_3(1:end))); P_pv2e_save3(idx_start:idx_end) = zero_tiny(value(P_pv2e_3(1:end)));
            P_e2el_save3(idx_start:idx_end) = zero_tiny(value(P_e2el_3(1:end))); P_el2H_save3(idx_start:idx_end) = zero_tiny(value(P_el2H_3(1:end)));
            P_H2mr_save3(idx_start:idx_end) = zero_tiny(value(P_H2mr_3(1:end))); P_mr2g_save3(idx_start:idx_end) = zero_tiny(value(P_mr2g_3(1:end)));
            P_H2hfc_save3(idx_start:idx_end) = zero_tiny(value(P_H2hfc_3(1:end))); P_hfc2e_save3(idx_start:idx_end) = zero_tiny(value(P_hfc2e_3(1:end))); P_hfc2h_save3(idx_start:idx_end) = zero_tiny(value(P_hfc2h_3(1:end)));
    
            P_g2gt_save3(idx_start:idx_end) = zero_tiny(value(P_g2gt_3(1:end)));
            P_H2gt_save3(idx_start:idx_end) = zero_tiny(value(LHV_H2*M_H2gt_3(1:end))); P_CH42gt_save3(idx_start:idx_end) = zero_tiny(value(LHV_CH4*M_g2gt_3(1:end)));
            V_H2gt_save3(idx_start:idx_end) = zero_tiny(value(V_H2gt_3(1:end))); V_g2gt_save3(idx_start:idx_end) = zero_tiny(value(V_g2gt_3(1:end)));
            M_H2gt_save3(idx_start:idx_end) = zero_tiny(value(M_H2gt_3(1:end))); M_g2gt_save3(idx_start:idx_end) = zero_tiny(value(M_g2gt_3(1:end)));
            P_gt2e_save3(idx_start:idx_end) = zero_tiny(value(P_gt2e_3(1:end))); P_gt2h_save3(idx_start:idx_end) = zero_tiny(value(P_gt2h_3(1:end)));
    
            P_g2gb_save3(idx_start:idx_end) = zero_tiny(value(P_g2gb_3(1:end)));
            P_H2gb_save3(idx_start:idx_end) = zero_tiny(value(LHV_H2*M_H2gb_3(1:end))); P_CH42gb_save3(idx_start:idx_end) = zero_tiny(value(LHV_CH4*M_g2gb_3(1:end)));
            V_H2gb_save3(idx_start:idx_end) = zero_tiny(value(V_H2gb_3(1:end))); V_g2gb_save3(idx_start:idx_end) = zero_tiny(value(V_g2gb_3(1:end)));
            M_H2gb_save3(idx_start:idx_end) = zero_tiny(value(M_H2gb_3(1:end))); M_g2gb_save3(idx_start:idx_end) = zero_tiny(value(M_g2gb_3(1:end)));
            P_gb2h_save3(idx_start:idx_end) = zero_tiny(value(P_gb2h_3(1:end)));
    
            P_e2eb_save3(idx_start:idx_end) = zero_tiny(value(P_e2eb_3(1:end))); P_eb2h_save3(idx_start:idx_end) = zero_tiny(value(P_eb2h_3(1:end)));
            %-------------------------------------------储能决策变量保存
            P_bat_cha_save3(idx_start:idx_end) = zero_tiny(value(P_bat_cha_3(1:end))); P_bat_dis_save3(idx_start:idx_end) = zero_tiny(value(P_bat_dis_3(1:end)));
            SOC_bat_save3(idx_start:idx_end+1) = zero_tiny(value(SOC_bat_3(1:end)));
            Flag_bat_cha_save3(idx_start:idx_end) = zero_tiny(value(Flag_bat_cha_3(1:end))); Flag_bat_dis_save3(idx_start:idx_end) = zero_tiny(value(Flag_bat_dis_3(1:end)));
    
            P_hst_cha_save3(idx_start:idx_end) = zero_tiny(value(P_hst_cha_3(1:end))); P_hst_dis_save3(idx_start:idx_end) = zero_tiny(value(P_hst_dis_3(1:end)));
            SOC_hst_save3(idx_start:idx_end+1) = zero_tiny(value(SOC_hst_3(1:end)));
            Flag_hst_cha_save3(idx_start:idx_end) = zero_tiny(value(Flag_hst_cha_3(1:end))); Flag_hst_dis_save3(idx_start:idx_end) = zero_tiny(value(Flag_hst_dis_3(1:end)));
    
            P_tst_cha_save3(idx_start:idx_end) = zero_tiny(value(P_tst_cha_3(1:end))); P_tst_dis_save3(idx_start:idx_end) = zero_tiny(value(P_tst_dis_3(1:end)));
            SOC_tst_save3(idx_start:idx_end+1) = zero_tiny(value(SOC_tst_3(1:end)));
            Flag_tst_cha_save3(idx_start:idx_end) = zero_tiny(value(Flag_tst_cha_3(1:end))); Flag_tst_dis_save3(idx_start:idx_end) = zero_tiny(value(Flag_tst_dis_3(1:end)));
    
            P_gst_cha_save3(idx_start:idx_end) = zero_tiny(value(P_gst_cha_3(1:end))); P_gst_dis_save3(idx_start:idx_end) = zero_tiny(value(P_gst_dis_3(1:end)));
            SOC_gst_save3(idx_start:idx_end+1) = zero_tiny(value(SOC_gst_3(1:end)));
            Flag_gst_cha_save3(idx_start:idx_end) = zero_tiny(value(Flag_gst_cha_3(1:end))); Flag_gst_dis_save3(idx_start:idx_end) = zero_tiny(value(Flag_gst_dis_3(1:end)));
            %----------------------------------------------------------------------购能决策变量保存
            P_pur_e_save3(idx_start:idx_end) = zero_tiny(value(P_pur_e_3(1:end))); P_pur_g_save3(idx_start:idx_end) = zero_tiny(value(P_pur_g_3(1:end)));
            %----------------------------------------------------------------------DR决策变量保存
            L_edr_cl_save3(idx_start:idx_end) = zero_tiny(value(L_edr_cl_3(1:end))); L_hdr_cl_save3(idx_start:idx_end) = zero_tiny(value(L_hdr_cl_3(1:end)));
            %----------------------------------------------------------------------阶梯碳交易决策变量保存
            P_e2ccs_save3(idx_start:idx_end) = zero_tiny(value(P_e2ccs_3(1:end)));
        end %IF_VALUE_Realtime

    end  %for j=1:3:12  % 30min-5min, 15min滚动一次，所以i+3，j：1,4,7,10

%% ****** 三、实时阶段(结尾特殊迭代) ***************************************
else    % if i == 81
    for j=1:3:43    % 30min-5min, 15min滚动一次，所以j+3。最后一次日内迭代，需要进行15次迭代
        OBJECTIVE_3 = 0;
        CONSTRAINTS_3 = [];
        % ==================== 公共参数 ====================
        % 使用相对索引推导出绝对索引位置，5min数据一共288个
        idx_start = (i-1)*3 + j;                            % 注意：本文件运行在日内for循环的内层，i是外层for的循环变量，禁止点击修复，忽略这种警告
        idx_end = (i-1)*3 + j + 5;
        % ==================== 源荷参数 ====================
        P_wt2e_max_3 = P_wt2e_5min_pre(idx_start:idx_end);
        P_pv2e_max_3 = P_pv2e_5min_pre(idx_start:idx_end);
        P_eLoad_3 = P_eLoad_5min_pre(idx_start:idx_end);
        P_hLoad_3 = P_hLoad_5min_pre(idx_start:idx_end);
        % ==================== 电价气价 ====================
        c_pur_e_3 = c_pur_e_288(idx_start:idx_end);
        c_pur_g_3 = c_pur_g_288(idx_start:idx_end);
        % ==================== 日内功率参考值，用于计算调整成本 ====================
        P_g2gt_save2_3 = P_g2gt_save2_288(idx_start:idx_end);
        P_g2gb_save2_3 = P_g2gb_save2_288(idx_start:idx_end);
    
        P_e2el_save2_3 = P_e2el_save2_288(idx_start:idx_end);
        P_H2mr_save2_3 = P_H2mr_save2_288(idx_start:idx_end);
        P_e2eb_save2_3 = P_e2eb_save2_288(idx_start:idx_end);

        P_hst_cha_save2_3 = P_hst_cha_save2_288(idx_start:idx_end);
        P_hst_dis_save2_3 = P_hst_dis_save2_288(idx_start:idx_end);
        P_tst_cha_save2_3 = P_tst_cha_save2_288(idx_start:idx_end);
        P_tst_dis_save2_3 = P_tst_dis_save2_288(idx_start:idx_end);
        P_gst_cha_save2_3 = P_gst_cha_save2_288(idx_start:idx_end);
        P_gst_dis_save2_3 = P_gst_dis_save2_288(idx_start:idx_end);
        % ==================== 日前DR_CL响应量 ====================
        L_edr_cl_save1_3 = L_edr_cl_save1_288(idx_start:idx_end);
        L_hdr_cl_save1_3 = L_hdr_cl_save1_288(idx_start:idx_end);
        % ==================== 日前DR_SL响应量 ====================
        L_edr_sl_in_save1_3 = L_edr_sl_in_save1_288(idx_start:idx_end);
        L_edr_sl_out_save1_3 = L_edr_sl_out_save1_288(idx_start:idx_end);
        L_hdr_sl_in_save1_3 = L_hdr_sl_in_save1_288(idx_start:idx_end);
        L_hdr_sl_out_save1_3 = L_hdr_sl_out_save1_288(idx_start:idx_end);
        % ==================== 日内DR响应量 ====================
        L_edr_cl_save2_3 = L_edr_cl_save2_288(idx_start:idx_end);
        L_hdr_cl_save2_3 = L_hdr_cl_save2_288(idx_start:idx_end);
        % 风机光伏
        CONSTRAINTS_3 = [CONSTRAINTS_3,...
            (0 <= P_wt2e_3 <= P_wt2e_max_3): 'P_wt2e_3',...
            (0 <= P_pv2e_3 <= P_pv2e_max_3): 'P_pv2e_3'
            ];
        % 笔记
        % 约束：首尾Delta、中间Delta、中间相等
        % EL电解槽（爬升约束）
        temp_el_3 = reshape(P_e2el_3, 3, []);  % 只是P_e2el_3的另一种视图，本质还是在操作P_e2el_3
        CONSTRAINTS_3 = [CONSTRAINTS_3,...
            (P_el2H_3 == f_el * P_e2el_3): 'P_el2H_3',...
            (P_el_min <= P_e2el_3 <= P_el_max): 'P_e2el_3',...
            (-Delta_el*P_el_max/4 <= P_e2el_3(1)-P_e2el_save3(idx_start-1) <= Delta_el*P_el_max/4): 'P_e2el(0)_Delta',...
            (-Delta_el*P_el_max/4 <= P_e2el_3(4)-P_e2el_3(3) <= Delta_el*P_el_max/4): 'P_e2el_Delta',...
            (temp_el_3(1:2, :) == temp_el_3(2:3, :))
            ];
        % MR甲烷反应器（爬升约束）
        temp_mr_3 = reshape(P_H2mr_3, 3, []);  % 只是P_H2mr_3的另一种视图，本质还是在操作P_H2mr_3
        CONSTRAINTS_3 = [CONSTRAINTS_3,...
            (P_mr2g_3 == f_mr * P_H2mr_3): 'P_mr2g_3',...
            (P_mr_min <= P_H2mr_3 <= P_mr_max): 'P_H2mr_3',...
            (-Delta_mr*P_mr_max/4 <= P_H2mr_3(1)-P_H2mr_save3(idx_start-1) <= Delta_mr*P_mr_max/4): 'P_H2mr(0)_Delta',...
            (-Delta_mr*P_mr_max/4 <= P_H2mr_3(4)-P_H2mr_3(3) <= Delta_mr*P_mr_max/4): 'P_H2mr_Delta',...
            (temp_mr_3(1:2, :) == temp_mr_3(2:3, :))
            ];
        % HFC燃料电池（爬升约束）
        CONSTRAINTS_3 = [CONSTRAINTS_3,...
            (P_hfc2e_3 == f_hfc_H2e * P_H2hfc_3): 'P_hfc2e_3',...
            (P_hfc2h_3 == f_hfc_H2h * P_H2hfc_3): 'P_hfc2h_3',...
            (P_hfc2e_3 + P_hfc2h_3 == (f_hfc_H2e+f_hfc_H2h) * P_H2hfc_3): 'P_hfc2e_3 + P_hfc2h_3',...
            (P_hfc_min <= P_H2hfc_3 <= P_hfc_max): 'P_H2hfc_3',...
            (-Delta_hfc*P_hfc_max/12 <= P_H2hfc_3(1)-P_H2hfc_save3(idx_start-1) <= Delta_hfc*P_hfc_max/12): 'P_H2hfc(0)_Delta',...
            (-Delta_hfc*P_hfc_max/12 <= P_H2hfc_3(2:end)-P_H2hfc_3(1:end-1) <= Delta_hfc*P_hfc_max/12): 'P_H2hfc_Delta'
            ];
        % GT燃气轮机（爬升约束）
        temp_gt_3 = reshape(P_g2gt_3, 3, []);    % 6x1 --> 3x2
        if  ismember(j, [1, 7, 13, 19, 25, 31, 37, 43])
            CONSTRAINTS_3 = [CONSTRAINTS_3,...
                (P_g2gt_3 == (LHV_CH4 * M_g2gt_3 + LHV_H2 * M_H2gt_3) ): 'M_H2gt_3',...
                (V_g2gt_3 == M_g2gt_3 / density_CH4): 'V_g2gt_3',...
                (V_H2gt_3 == M_H2gt_3 / density_H2): 'V_H2gt_3',...
                (V_H2gt_3 <= k_H2gt_upper * (V_g2gt_3 + V_H2gt_3)): 'k_H2gt_upper',...
                (V_H2gt_3 >= k_H2gt_lower * (V_g2gt_3 + V_H2gt_3)): 'k_H2gt_lower',...
                (P_gt2e_3 == f_gt_g2e * P_g2gt_3): 'P_gt2e_3',...
                (P_gt2h_3 == f_gt_g2h * P_g2gt_3): 'P_gt2h_3',...
                (P_gt2e_3 + P_gt2h_3 == (f_gt_g2e+f_gt_g2h) * P_g2gt_3): 'P_gt2e_3 + P_gt2h_3',...
                (P_gt_min <= P_g2gt_3 <= P_gt_max): 'P_g2gt_3',...
                (-Delta_gt*P_gt_max/2 <= P_g2gt_3(1) - P_g2gt_save3(idx_start-1) <= Delta_gt*P_gt_max/2): 'P_g2gt(0)_Detla',...
                (P_g2gt_3(2:end) == P_g2gt_3(1:end-1)),...
                (M_g2gt_3 >= 0),...
                (M_H2gt_3 >= 0)
                ];
        elseif ismember(j, [4, 10, 16, 22, 28, 34, 40])
            CONSTRAINTS_3 = [CONSTRAINTS_3,...
                (P_g2gt_3 == (LHV_CH4 * M_g2gt_3 + LHV_H2 * M_H2gt_3) ): 'M_H2gt_3',...
                (V_g2gt_3 == M_g2gt_3 / density_CH4): 'V_g2gt_3',...
                (V_H2gt_3 == M_H2gt_3 / density_H2): 'V_H2gt_3',...
                (V_H2gt_3 <= k_H2gt_upper * (V_g2gt_3 + V_H2gt_3)): 'k_H2gt_upper',...
                (V_H2gt_3 >= k_H2gt_lower * (V_g2gt_3 + V_H2gt_3)): 'k_H2gt_lower',...
                (P_gt2e_3 == f_gt_g2e * P_g2gt_3): 'P_gt2e_3',...
                (P_gt2h_3 == f_gt_g2h * P_g2gt_3): 'P_gt2h_3',...
                (P_gt2e_3 + P_gt2h_3 == (f_gt_g2e+f_gt_g2h) * P_g2gt_3): 'P_gt2e_3 + P_gt2h_3',...
                (P_gt_min <= P_g2gt_3 <= P_gt_max): 'P_g2gt_3',...
                (-Delta_gt*P_gt_max/2 <= P_g2gt_3(1) - P_g2gt_save3(idx_start-1) <= Delta_gt*P_gt_max/2): 'P_g2gt(0)_Detla',...
                (-Delta_gt*P_gt_max/2 <= P_g2gt_3(4) - P_g2gt_3(3) <= Delta_gt*P_gt_max/2): 'P_g2gt_3_Detla',...
                (temp_gt_3(1:2, :) == temp_gt_3(2:3, :)),...
                (M_g2gt_3 >= 0),...
                (M_H2gt_3 >= 0)
                ];
        end
        % GB燃气轮机（爬升约束）
        temp_gb_3 = reshape(P_g2gb_3, 3, []);    % 6x1 --> 3x2
        if ismember(j, [1, 7, 13, 19, 25, 31, 37, 43])
            CONSTRAINTS_3 = [CONSTRAINTS_3,...
                (P_g2gb_3 == (LHV_CH4 * M_g2gb_3 + LHV_H2 * M_H2gb_3) ): 'M_H2gb_3',...
                (V_g2gb_3 == M_g2gb_3 / density_CH4): 'V_g2gb_3',...
                (V_H2gb_3 == M_H2gb_3 / density_H2): 'V_H2gb_3',...
                (V_H2gb_3 <= k_H2gb_upper * (V_g2gb_3 + V_H2gb_3)): 'k_H2gb_upper',...
                (V_H2gb_3 >= k_H2gb_lower * (V_g2gb_3 + V_H2gb_3)): 'k_H2gb_lower',...
                (P_gb2h_3 == f_gb * P_g2gb_3): 'P_gb2h_3',...
                (P_gb_min <= P_g2gb_3 <= P_gb_max): 'P_g2gb_3',...
                (-Delta_gb*P_gb_max/2 <= P_g2gb_3(1) - P_g2gb_save3(idx_start-1) <= Delta_gb*P_gb_max/2): 'P_g2gb(0)_Detla',...
                (P_g2gb_3(2:end) == P_g2gb_3(1:end-1)),...
                (M_g2gb_3 >= 0),...
                (M_H2gb_3 >= 0)
                ];
        elseif ismember(j, [4, 10, 16, 22, 28, 34, 40])
            CONSTRAINTS_3 = [CONSTRAINTS_3,...
                (P_g2gb_3 == (LHV_CH4 * M_g2gb_3 + LHV_H2 * M_H2gb_3) ): 'M_H2gb_3',...
                (V_g2gb_3 == M_g2gb_3 / density_CH4): 'V_g2gb_3',...
                (V_H2gb_3 == M_H2gb_3 / density_H2): 'V_H2gb_3',...
                (V_H2gb_3 <= k_H2gb_upper * (V_g2gb_3 + V_H2gb_3)): 'k_H2gb_upper',...
                (V_H2gb_3 >= k_H2gb_lower * (V_g2gb_3 + V_H2gb_3)): 'k_H2gb_lower',...
                (P_gb2h_3 == f_gb * P_g2gb_3): 'P_gb2h_3',...
                (P_gb_min <= P_g2gb_3 <= P_gb_max): 'P_g2gb_3',...
                (-Delta_gb*P_gb_max/2 <= P_g2gb_3(1) - P_g2gb_save3(idx_start-1) <= Delta_gb*P_gb_max/2): 'P_g2gb(0)_Detla',...
                (-Delta_gb*P_gb_max/2 <= P_g2gb_3(4) - P_g2gb_3(3) <= Delta_gb*P_gb_max/2): 'P_g2gb_3_Detla',...
                (temp_gb_3(1:2, :) == temp_gb_3(2:3, :)),...
                (M_g2gb_3 >= 0),...
                (M_H2gb_3 >= 0)
                ];
        end
        % EB电锅炉（爬升约束）
        temp_eb_3 = reshape(P_e2eb_3, 3, []);
        CONSTRAINTS_3 = [CONSTRAINTS_3,...
            (P_eb2h_3 == f_eb * P_e2eb_3): 'P_eb2h_3',...
            (P_eb_min <= P_e2eb_3 <= P_eb_max): 'P_e2eb_3',...
            (-Delta_eb*P_eb_max/4 <= P_e2eb_3(1)-P_e2eb_save3(idx_start-1) <= Delta_eb*P_eb_max/4): 'P_e2eb(0)_Delta',...
            (-Delta_eb*P_eb_max/4 <= P_e2eb_3(4)-P_e2eb_3(3) <= Delta_eb*P_eb_max/4): 'P_e2eb_Delta',...
            (temp_eb_3(1:2, :) == temp_eb_3(2:3, :))
            ];
        %% ======== 3.储能约束 ===================================
        % 储电约束Battery，充放能倍率选择0.5C
        CONSTRAINTS_3 = [CONSTRAINTS_3,...
            (0 <= P_bat_cha_3 <= Flag_bat_cha_3 * Q_bat_max * 0.5): 'P_bat_cha_3',...
            (0 <= P_bat_dis_3 <= Flag_bat_dis_3 * Q_bat_max * 0.5): 'P_bat_dis_3',...
            (Flag_bat_cha_3 + Flag_bat_dis_3 <= 1): 'Flag_bat',...
            (SOC_bat_3(1) == SOC_bat_save3(idx_start)): 'SOC_bat_init',...
            (f_bat_min <= SOC_bat_3 <= f_bat_max): 'SOC_bat_range',...
            (SOC_bat_3(2:end) == SOC_bat_3(1:end-1) + f_bat_cha/(Q_bat_max*12)*P_bat_cha_3 - P_bat_dis_3/(f_bat_dis*Q_bat_max*12)): 'SOC_bat_Delta'
            ];
        % 储氢约束HST
        CONSTRAINTS_3 = [CONSTRAINTS_3,...
            (0 <= P_hst_cha_3 <= Flag_hst_cha_3 * Q_hst_max * 0.5): 'P_hst_cha_3',...
            (0 <= P_hst_dis_3 <= Flag_hst_dis_3 * Q_hst_max * 0.5): 'P_hst_dis_3',...
            (Flag_hst_cha_3 + Flag_hst_dis_3 <= 1): 'Flag_hst',...
            (SOC_hst_3(1) == SOC_hst_save3(idx_start)): 'SOC_hst_init',...
            (f_hst_min <= SOC_hst_3 <= f_hst_max): 'SOC_hst_range',...
            (SOC_hst_3(2:end) == SOC_hst_3(1:end-1) + f_hst_cha/(Q_hst_max*12)*P_hst_cha_3 - P_hst_dis_3/(f_hst_dis*Q_hst_max*12)): 'SOC_hst_Delta'
            ];
        % 储热约束TST
        CONSTRAINTS_3 = [CONSTRAINTS_3,...
            (0 <= P_tst_cha_3 <= Flag_tst_cha_3 * Q_tst_max * 0.5): 'P_tst_cha_3',...
            (0 <= P_tst_dis_3 <= Flag_tst_dis_3 * Q_tst_max * 0.5): 'P_tst_dis_3',...
            (Flag_tst_cha_3 + Flag_tst_dis_3 <= 1): 'Flag_tst',...
            (SOC_tst_3(1) == SOC_tst_save3(idx_start)): 'SOC_tst_init',...
            (f_tst_min <= SOC_tst_3 <= f_tst_max): 'SOC_tst_range',...
            (SOC_tst_3(2:end) == SOC_tst_3(1:end-1) + f_tst_cha/(Q_tst_max*12)*P_tst_cha_3 - P_tst_dis_3/(f_tst_dis*Q_tst_max*12)): 'SOC_tst_Delta'
            ];
        % 储气约束GST
        CONSTRAINTS_3 = [CONSTRAINTS_3,...
            (0 <= P_gst_cha_3 <= Flag_gst_cha_3 * Q_gst_max * 0.5): 'P_gst_cha_3',...
            (0 <= P_gst_dis_3 <= Flag_gst_dis_3 * Q_gst_max * 0.5): 'P_gst_dis_3',...
            (Flag_gst_cha_3 + Flag_gst_dis_3 <= 1): 'Flag_gst',...
            (SOC_gst_3(1) == SOC_gst_save3(idx_start)): 'SOC_gst_init',...
            (f_gst_min <= SOC_gst_3 <= f_gst_max): 'SOC_gst_range',...
            (SOC_gst_3(2:end) == SOC_gst_3(1:end-1) + f_gst_cha/(Q_gst_max*12)*P_gst_cha_3 - P_gst_dis_3/(f_gst_dis*Q_gst_max*12)): 'SOC_gst_Delta'
            ];
        % 这里添加软约束 SOC(end)=SOC(init) 的偏差惩罚，硬约束会导致无解。Gemini给的修改建议，简直无敌了，牛皮。
        if j == 43
            % 计算此时刻 SOC_end 与 初始值 的偏差
            penalty_weight = 6000;
            C_soc_penalty = penalty_weight * ( ...
                abs(SOC_bat_3(end) - f_bat_init) + ...
                abs(SOC_hst_3(end) - f_hst_init) + ...
                abs(SOC_tst_3(end) - f_tst_init) + ...
                abs(SOC_gst_3(end) - f_gst_init) );
        else
            C_soc_penalty = 0;
        end
        %% ======== 4.1购能约束 ===================================
        % 购电、购气约束
        CONSTRAINTS_3 = [CONSTRAINTS_3,...
            (0 <= P_pur_e_3 <= P_pur_e_max): 'P_pur_e_3',...
            (0 <= P_pur_g_3 <= P_pur_g_max): 'P_pur_g_3'
            ];
        %% ======== 4.2DR约束 ===================================
        CONSTRAINTS_3 = [CONSTRAINTS_3,...
            (0 <= L_edr_cl_3 <= L_edr_cl_max_3): 'L_edr_cl_3',...
            (0 <= L_hdr_cl_3 <= L_hdr_cl_max_3): 'L_hdr_cl_3',...
            ];
        %% ======== 4.3阶梯碳交易 ===================================
        % 实际碳排放，这里只计算天然气部分产生的二氧化碳
        E_actu_e2pur_3 = sum( k_SC_a + k_SC_b*P_pur_e_3 + k_SC_c*(P_pur_e_3.^2) ) / 12;          % 电网实际碳排放量
        P_gt_total_3 = LHV_CH4*M_g2gt_3*f_gt_g2e*phi_eh + LHV_CH4*M_g2gt_3*f_gt_g2h;
        E_actu_gt_3 = sum( k_gas_a + k_gas_b*P_gt_total_3 + k_gas_c*(P_gt_total_3.^2) ) / 12;    % GT实际碳排放量
        P_gb_total_3 = LHV_CH4*M_g2gb_3*f_gb;
        E_actu_gb_3 = sum( k_gas_a + k_gas_b*P_gb_total_3 + k_gas_c*(P_gb_total_3.^2) ) / 12;    % GB实际碳排放量
        E_actu_total_3 = E_actu_e2pur_3 + E_actu_gt_3 + E_actu_gb_3;
        % CCS吸收碳排放量
        E_ccs_total_3 = sum( P_mr2g_3 / LHV_CH4 * w_mr) / 12;
        CONSTRAINTS_3 = [CONSTRAINTS_3,...
            (P_e2ccs_3 == P_mr2g_3 / LHV_CH4 * w_mr * f_ccus): 'P_e2ccs_3'
            ];
        % 碳配额部分
        E_pe_total_3 = E_pe_total_save1 / (E_actu_total_save1 - E_ccs_total_save1) * (E_actu_total_3 - E_ccs_total_3);
        % 碳交易
        E_tra_3 = E_actu_total_3 - E_pe_total_3 - E_ccs_total_3;     % 参与碳交易的二氧化碳量
        C_lad_CO2_3 = c_lad_di_da * E_tra_3;

        %% ======== 5.功率平衡约束 ===================================
        CONSTRAINTS_3 = [CONSTRAINTS_3,...
            ... 电平衡：风光发电 + 电网购电 + GT发电 + HFC发电 + 电池放电 = 电负荷 + EL电解槽电解 + EB电锅炉用电 + CCS用电 +电池充电 -日前DR_CL+日前DR_SL_in-日前DR_SL_out-日内DR_CL-实时DR_CL
            (P_wt2e_3+P_pv2e_3+P_pur_e_3+P_gt2e_3+P_hfc2e_3+P_bat_dis_3 ==  P_eLoad_3+P_e2el_3+P_e2eb_3+P_e2ccs_3+P_bat_cha_3-L_edr_cl_save1_3+L_edr_sl_in_save1_3-L_edr_sl_out_save1_3-L_edr_cl_save2_3-L_edr_cl_3): 'P_e_balance',...
            ... 热平衡：GT产热 + GB产热 + HFC产热 + EB产热 + 储热放热 = 热负荷 + 储热吸热 -日前DR_CL+日前DR_SL_in-日前DR_SL_out-日内DR_CL-实时DR_CL
            (P_gt2h_3 + P_gb2h_3 + P_hfc2h_3 + P_eb2h_3 + P_tst_dis_3 == P_hLoad_3 + P_tst_cha_3-L_hdr_cl_save1_3+L_hdr_sl_in_save1_3-L_hdr_sl_out_save1_3-L_hdr_cl_save2_3-L_hdr_cl_3): 'P_h_balance',...
            ... 氢平衡：EL产氢 + 储氢放氢 = HFC用氢 + MR用氢 + GT用氢 + GB用氢 + 储氢充氢
            (P_el2H_3 + P_hst_dis_3 == P_H2hfc_3 + P_H2mr_3 + LHV_H2*M_H2gt_3 + LHV_H2*M_H2gb_3 + P_hst_cha_3): 'P_H_balance',...
            ... 气平衡：气网购气 + MR产气 + 储气放气 = GT用气 + GB用气 + 储气充气
            (P_pur_g_3 + P_mr2g_3 + P_gst_dis_3 == LHV_CH4*M_g2gt_3 + LHV_CH4*M_g2gb_3 + P_gst_cha_3): 'P_g_balance'
            ];
        %% ======== 6.目标函数 ===================================
        % ==================== 运维成本 ====================
        C_opm_3 = ( sum(P_wt2e_3)*c_opm_wt + sum(P_pv2e_3)*c_opm_pv + sum(P_e2el_3)*c_opm_el + sum(P_H2hfc_3)*c_opm_hfc + ...
            sum(P_g2gt_3)*c_opm_gt + sum(P_g2gb_3)*c_opm_gb + sum(P_e2eb_3)*c_opm_eb ) / 12;
        % ==================== 购能成本 ====================
        % 注意：天然气价格为 元/m3，所以需要转换单位
        C_pur_3 = ( sum(P_pur_e_3.*c_pur_e_3) + sum( P_pur_g_3 / (LHV_CH4 * density_CH4) .* c_pur_g_3 )) / 12;
        % ==================== 储能成本 ====================
        C_st_3 = ( sum(P_bat_cha_3+P_bat_dis_3)*c_st_bat + sum(P_hst_cha_3+P_hst_dis_3)*c_st_hst + sum(P_tst_cha_3+P_tst_dis_3)*c_st_tst + ...
            sum(P_gst_cha_3+P_gst_dis_3)*c_st_gst ) / 12;
        % ==================== 弃能成本 ====================
        C_abd_3 = ( sum(P_wt2e_max_3 - P_wt2e_3)*c_abd_wt + sum(P_pv2e_max_3 - P_pv2e_3)*c_abd_pv ) / 12;
        % ==================== 调整成本（新增） ====================
        C_adj_3 = ( sum(abs(P_g2gt_3 - P_g2gt_save2_3))*c_adj_3 + sum(abs(P_g2gb_3 - P_g2gb_save2_3)) * c_adj_3 + ...
            sum(abs(P_e2el_3 - P_e2el_save2_3))*c_adj_3 + sum(abs(P_H2mr_3 - P_H2mr_save2_3))*c_adj_3 + sum(abs(P_e2eb_3 - P_e2eb_save2_3))*c_adj_3 +...
            sum(abs(P_hst_cha_3 - P_hst_cha_save2_3))*c_adj_3 +  sum(abs(P_hst_dis_3 - P_hst_dis_save2_3))*c_adj_3 + ...
            sum(abs(P_tst_cha_3 - P_tst_cha_save2_3))*c_adj_3 +  sum(abs(P_tst_dis_3 - P_tst_dis_save2_3))*c_adj_3 + ...
            sum(abs(P_gst_cha_3 - P_gst_cha_save2_3))*c_adj_3 +  sum(abs(P_gst_dis_3 - P_gst_dis_save2_3))*c_adj_3 ) / 12;
        % ==================== DR成本 ====================
        C_dr_3 = ( sum(L_edr_cl_3)*c_edr_cl_3 + sum(L_hdr_cl_3)*c_hdr_cl_3 ) / 12;
        %% ======== 7.求解 ===================================
        OBJECTIVE_3 = OBJECTIVE_3 + C_opm_3 + C_pur_3 + C_st_3 + C_abd_3 + C_adj_3 + C_dr_3 + C_soc_penalty + C_lad_CO2_3;
        OPTIONS = sdpsettings('solver', 'cplex', 'verbose', 0, 'showprogress', 0);
        % 在数学优化中，容差参数用于处理数值计算中的舍入误差和数值不稳定性。由于计算机使用浮点数运算，严格的等式约束在实际中很难完全满足

        % if i==81 && j==7
        %     fprintf("DBG i=%d j=%d idx_start=%d idx_end=%d\n", i, j, idx_start, idx_end);
        % 
        %     fprintf("SOC_bat_save3(idx_start)=%g, SOC_bat_save3(idx_start-1)=%g\n", ...
        %         SOC_bat_save3(idx_start), SOC_bat_save3(idx_start-1));
        %     fprintf("SOC_hst_save3(idx_start)=%g, SOC_hst_save3(idx_start-1)=%g\n", ...
        %         SOC_hst_save3(idx_start), SOC_hst_save3(idx_start-1));
        %     fprintf("SOC_tst_save3(idx_start)=%g, SOC_tst_save3(idx_start-1)=%g\n", ...
        %         SOC_tst_save3(idx_start), SOC_tst_save3(idx_start-1));
        %     fprintf("SOC_gst_save3(idx_start)=%g, SOC_gst_save3(idx_start-1)=%g\n", ...
        %         SOC_gst_save3(idx_start), SOC_gst_save3(idx_start-1));
        % 
        %     fprintf("P_e2el_save3(idx_start-1)=%g\n", P_e2el_save3(idx_start-1));
        %     fprintf("P_H2mr_save3(idx_start-1)=%g\n", P_H2mr_save3(idx_start-1));
        %     fprintf("P_H2hfc_save3(idx_start-1)=%g\n", P_H2hfc_save3(idx_start-1));
        %     fprintf("P_g2gt_save3(idx_start-1)=%g\n", P_g2gt_save3(idx_start-1));
        %     fprintf("P_g2gb_save3(idx_start-1)=%g\n", P_g2gb_save3(idx_start-1));
        %     fprintf("P_e2eb_save3(idx_start-1)=%g\n", P_e2eb_save3(idx_start-1));
        % end


        OPTIONS.cplex.eprhs = 1e-6;     % 可行性容差
        OPTIONS.cplex.epopt = 1e-6;     % 最优性容差
        sol = optimize(CONSTRAINTS_3, OBJECTIVE_3, OPTIONS);
    
        if sol.problem == 0
            win = (j-1)/3 + 1;
            fprintf("    实时滚动窗口 %d（起点索引 i=%d）求解成功\n", win, j);
    
        else 
            disp("    出错了，原因是：");
            disp(sol.info);
    
            % 正确的调试方法
            if sol.problem == 1
                disp("    问题不可行，检查约束条件");
                % 检查哪些约束不满足
                disp("    检查约束可行性:");
                check(CONSTRAINTS_3);
            else
                disp(["    求解器返回代码: ", num2str(sol.problem)]);
            end
        end  %if sol.problem == 0 
    
    
        %% ======== 8.保存30min-5min求解值 ===================================
        if IF_VALUE_Realtime        
            %-------------------------------------------设备决策变量保存
            P_wt2e_save3(idx_start:idx_end) = zero_tiny(value(P_wt2e_3(1:end))); P_pv2e_save3(idx_start:idx_end) = zero_tiny(value(P_pv2e_3(1:end)));
            P_e2el_save3(idx_start:idx_end) = zero_tiny(value(P_e2el_3(1:end))); P_el2H_save3(idx_start:idx_end) = zero_tiny(value(P_el2H_3(1:end)));
            P_H2mr_save3(idx_start:idx_end) = zero_tiny(value(P_H2mr_3(1:end))); P_mr2g_save3(idx_start:idx_end) = zero_tiny(value(P_mr2g_3(1:end)));
            P_H2hfc_save3(idx_start:idx_end) = zero_tiny(value(P_H2hfc_3(1:end))); P_hfc2e_save3(idx_start:idx_end) = zero_tiny(value(P_hfc2e_3(1:end))); P_hfc2h_save3(idx_start:idx_end) = zero_tiny(value(P_hfc2h_3(1:end)));
    
            P_g2gt_save3(idx_start:idx_end) = zero_tiny(value(P_g2gt_3(1:end)));
            P_H2gt_save3(idx_start:idx_end) = zero_tiny(value(LHV_H2*M_H2gt_3(1:end))); P_CH42gt_save3(idx_start:idx_end) = zero_tiny(value(LHV_CH4*M_g2gt_3(1:end)));
            V_H2gt_save3(idx_start:idx_end) = zero_tiny(value(V_H2gt_3(1:end))); V_g2gt_save3(idx_start:idx_end) = zero_tiny(value(V_g2gt_3(1:end)));
            M_H2gt_save3(idx_start:idx_end) = zero_tiny(value(M_H2gt_3(1:end))); M_g2gt_save3(idx_start:idx_end) = zero_tiny(value(M_g2gt_3(1:end)));
            P_gt2e_save3(idx_start:idx_end) = zero_tiny(value(P_gt2e_3(1:end))); P_gt2h_save3(idx_start:idx_end) = zero_tiny(value(P_gt2h_3(1:end)));
    
            P_g2gb_save3(idx_start:idx_end) = zero_tiny(value(P_g2gb_3(1:end)));
            P_H2gb_save3(idx_start:idx_end) = zero_tiny(value(LHV_H2*M_H2gb_3(1:end))); P_CH42gb_save3(idx_start:idx_end) = zero_tiny(value(LHV_CH4*M_g2gb_3(1:end)));
            V_H2gb_save3(idx_start:idx_end) = zero_tiny(value(V_H2gb_3(1:end))); V_g2gb_save3(idx_start:idx_end) = zero_tiny(value(V_g2gb_3(1:end)));
            M_H2gb_save3(idx_start:idx_end) = zero_tiny(value(M_H2gb_3(1:end))); M_g2gb_save3(idx_start:idx_end) = zero_tiny(value(M_g2gb_3(1:end)));
            P_gb2h_save3(idx_start:idx_end) = zero_tiny(value(P_gb2h_3(1:end)));
    
            P_e2eb_save3(idx_start:idx_end) = zero_tiny(value(P_e2eb_3(1:end))); P_eb2h_save3(idx_start:idx_end) = zero_tiny(value(P_eb2h_3(1:end)));
            %-------------------------------------------储能决策变量保存
            P_bat_cha_save3(idx_start:idx_end) = zero_tiny(value(P_bat_cha_3(1:end))); P_bat_dis_save3(idx_start:idx_end) = zero_tiny(value(P_bat_dis_3(1:end)));
            SOC_bat_save3(idx_start:idx_end+1) = zero_tiny(value(SOC_bat_3(1:end)));
            Flag_bat_cha_save3(idx_start:idx_end) = zero_tiny(value(Flag_bat_cha_3(1:end))); Flag_bat_dis_save3(idx_start:idx_end) = zero_tiny(value(Flag_bat_dis_3(1:end)));
    
            P_hst_cha_save3(idx_start:idx_end) = zero_tiny(value(P_hst_cha_3(1:end))); P_hst_dis_save3(idx_start:idx_end) = zero_tiny(value(P_hst_dis_3(1:end)));
            SOC_hst_save3(idx_start:idx_end+1) = zero_tiny(value(SOC_hst_3(1:end)));
            Flag_hst_cha_save3(idx_start:idx_end) = zero_tiny(value(Flag_hst_cha_3(1:end))); Flag_hst_dis_save3(idx_start:idx_end) = zero_tiny(value(Flag_hst_dis_3(1:end)));
    
            P_tst_cha_save3(idx_start:idx_end) = zero_tiny(value(P_tst_cha_3(1:end))); P_tst_dis_save3(idx_start:idx_end) = zero_tiny(value(P_tst_dis_3(1:end)));
            SOC_tst_save3(idx_start:idx_end+1) = zero_tiny(value(SOC_tst_3(1:end)));
            Flag_tst_cha_save3(idx_start:idx_end) = zero_tiny(value(Flag_tst_cha_3(1:end))); Flag_tst_dis_save3(idx_start:idx_end) = zero_tiny(value(Flag_tst_dis_3(1:end)));
    
            P_gst_cha_save3(idx_start:idx_end) = zero_tiny(value(P_gst_cha_3(1:end))); P_gst_dis_save3(idx_start:idx_end) = zero_tiny(value(P_gst_dis_3(1:end)));
            SOC_gst_save3(idx_start:idx_end+1) = zero_tiny(value(SOC_gst_3(1:end)));
            Flag_gst_cha_save3(idx_start:idx_end) = zero_tiny(value(Flag_gst_cha_3(1:end))); Flag_gst_dis_save3(idx_start:idx_end) = zero_tiny(value(Flag_gst_dis_3(1:end)));
            %----------------------------------------------------------------------购能决策变量保存
            P_pur_e_save3(idx_start:idx_end) = zero_tiny(value(P_pur_e_3(1:end))); P_pur_g_save3(idx_start:idx_end) = zero_tiny(value(P_pur_g_3(1:end)));
            %----------------------------------------------------------------------DR决策变量保存
            L_edr_cl_save3(idx_start:idx_end) = zero_tiny(value(L_edr_cl_3(1:end))); L_hdr_cl_save3(idx_start:idx_end) = zero_tiny(value(L_hdr_cl_3(1:end)));
            %----------------------------------------------------------------------阶梯碳交易决策变量保存
            P_e2ccs_save3(idx_start:idx_end) = zero_tiny(value(P_e2ccs_3(1:end)));
        end %IF_VALUE_Realtime
    end  %for j=1:3:45 
    
end  %if i ~= 81
